### ISSUE TITLE
hydration-errors

### ISSUE THREAD

**Issue by henningsieh** [ethanmick/nextauth-custom-login#1]
Hi, there are quite many of these hydration-errors in the console. 

```
Warning: Did not expect server HTML to contain a <div> in <div>.
div
form
Form@webpack-internal:///(app-client)/./app/(auth)/login/form.tsx:27:78
div
div
```

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Did not expect server HTML to contain a <div> in <div>.
```

Do you plan to fix all these? Thanks

**Comment by henningsieh** [comment]
ok lol... it was lastpass extension wtf!! *SRY

https://stackoverflow.com/questions/75241306/input-field-in-nextjs-causing-hydration-error-and-did-not-expect-server-html-to/75490907#75490907

**Comment by ethanmick** [comment]
!!!

Thanks for following up on this, I was going to spend some time later this week looking at it. I've found Grammarly also causes a mismatch that's annoying. When doing development I've started doing it in a clean chrome profile to avoid those issues.

Cheers!
